
package ryan.ramadhan.view;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import ryan.ramadhan.db.KoneksiDatabase;

/**
 * @author Ryan Ramadhan || 1910631170229
 */

public class viewLaporanTransaksi extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    
    public viewLaporanTransaksi() {
        initComponents();
        
        model = new DefaultTableModel();
        tabelTransaksi.setModel(model);
        model.addColumn("Tanggal");
        model.addColumn("Nama Barang");
        model.addColumn("QTY");
        model.addColumn("SubTotal");
        //tampilDataPenjualan();
        viewTahun.setText("2022");
        viewPemasukan.setDisabledTextColor(Color.black);
        viewTerjual.setDisabledTextColor(Color.black);
        viewPemasukan.disable();
        viewTerjual.disable();
    }

    public JComboBox<String> getViewBulan() {
        return viewBulan;
    }

    public void setViewBulan(JComboBox<String> viewBulan) {
        this.viewBulan = viewBulan;
    }

    public JTextField getViewPemasukan() {
        return viewPemasukan;
    }

    public void setViewPemasukan(JTextField viewPemasukan) {
        this.viewPemasukan = viewPemasukan;
    }

    public JTextField getViewTahun() {
        return viewTahun;
    }

    public void setViewTahun(JTextField viewTahun) {
        this.viewTahun = viewTahun;
    }

    public JTextField getViewTerjual() {
        return viewTerjual;
    }

    public void setViewTerjual(JTextField viewTerjual) {
        this.viewTerjual = viewTerjual;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewBulan = new javax.swing.JComboBox<>();
        viewTahun = new javax.swing.JTextField();
        viewCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        viewTerjual = new javax.swing.JTextField();
        viewPemasukan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Laporan Transaksi");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Transaksi Pada Bulan :");

        viewBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        viewBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBulanActionPerformed(evt);
            }
        });

        viewCari.setText("Cari");
        viewCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCariActionPerformed(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Detail Transaksi Bulanan :");

        jLabel3.setText("Total Barang Terjual :");

        jLabel4.setText("Total Pemasukan      :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(viewBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(viewTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewCari))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(104, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(viewTerjual))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(viewPemasukan)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(viewBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCari)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewTerjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBulanActionPerformed

    private void viewCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCariActionPerformed
    // TODO add your handling code here:
        int bulan = viewBulan.getSelectedIndex() + 1;
        int terjual = 0;
        int pemasukan = 0;
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        String sql = "SELECT * FROM transaksiDetail WHERE tanggal >= '"+viewTahun.getText()+"-"+bulan+"-1' AND tanggal <= '"
                +viewTahun.getText()+"-"+bulan+"-31'";
        try {
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while (res.next()) {                
                Object[] hasil;
                hasil = new Object[4];
                hasil[0] = res.getString("tanggal");
                hasil[1] = res.getString("namaBarang");
                hasil[2] = res.getString("qty");
                hasil[3] = res.getString("subTotal");
                
                terjual = terjual + Integer.parseInt(res.getString("qty"));
                pemasukan = pemasukan + Integer.parseInt(res.getString("subTotal"));
                
                model.addRow(hasil);
            }
            viewTerjual.setText(Integer.toString(terjual)+" Pcs");
            viewPemasukan.setText("Rp."+Integer.toString(pemasukan));
        } catch (SQLException e) {
            Logger.getLogger(viewPelangganInternal.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_viewCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JComboBox<String> viewBulan;
    private javax.swing.JButton viewCari;
    private javax.swing.JTextField viewPemasukan;
    private javax.swing.JTextField viewTahun;
    private javax.swing.JTextField viewTerjual;
    // End of variables declaration//GEN-END:variables
}
