
package ryan.ramadhan.view;

import ryan.ramadhan.controller.controllerPelanggan;
import ryan.ramadhan.db.KoneksiDatabase;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 * @author Ryan Ramadhan || 1910631170229
 */

public class viewPelangganInternal extends javax.swing.JInternalFrame {

    private DefaultTableModel model;
    private controllerPelanggan cP;
    
    public viewPelangganInternal() {
        initComponents();
        
        cP = new controllerPelanggan(this);
        model = new DefaultTableModel();
        tabelPelanggan.setModel(model);
        
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("NOHP");
        model.addColumn("JK");
        model.addColumn("UMUR");
        model.addColumn("ALAMAT");
        
        tampilDataPelanggan();
        cP.kontrolButton();
    }
  
        public JTextField getIdPelangganView(){
        return idPelangganView;
        }
        
        public JTextField getNamaPelangganView(){
            return namaPelangganView;
        }
        
        public JTextField getNoHpView(){
            return nomorHpView;
        }
        
        public JRadioButton getPriaView(){
            return pria;
        }
        
        public JRadioButton getWanitaView(){
            return wanita;
        }
        
        public JTextField getUmurView(){
            return umur;
        }
        
        public JTextArea getAlamatView(){
            return alamat;
        }
        
        public JButton getTombolSimpan(){
            return tombolSimpan;
        }
        
        public JButton getTombolHapus(){
            return tombolHapus;
        }
        
        public JButton getTombolEdit(){
            return tombolUbah;
        }
        
        public JButton getTombolBatal(){
            return tombolBatal;
        }
        
        
    //author Ryan Ramadhan || 1910631170229  
    private void tampilDataPelanggan(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        String sql = "SELECT * FROM pelanggan";
        
        try{
            Statement stat = (Statement) KoneksiDatabase.getKoneksi().createStatement();
            ResultSet res = stat.executeQuery(sql);
            
            while(res.next()){
                //Mengambil hasil query variabel sql
                Object[] hasil;
                hasil = new Object[6]; //terdapat 6 field pada tabel pelanggan
                hasil[0] = res.getString("idPelanggan");
                hasil[1] = res.getString("namaPelanggan");
                hasil[2] = res.getString("noHp");
                hasil[3] = res.getString("JenisKelamin");
                hasil[4] = res.getString("umur");
                hasil[5] = res.getString("alamat");
                
                model.addRow(hasil);
            }
        } catch(SQLException ex){
            Logger.getLogger(viewPelangganInternal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //author Ryan Ramadhan || 1910631170229
    private void ambilDataTabel(){
        int index = tabelPelanggan.getSelectedRow();
        
        String id = String.valueOf(tabelPelanggan.getValueAt(index, 0));
        String nama = String.valueOf(tabelPelanggan.getValueAt(index, 1));
        String nohp = String.valueOf(tabelPelanggan.getValueAt(index, 2));
        String jk = String.valueOf(tabelPelanggan.getValueAt(index, 3));
        String umr = String.valueOf(tabelPelanggan.getValueAt(index, 4));
        String almt = String.valueOf(tabelPelanggan.getValueAt(index, 5));
        
        //Mengisi nilai kedalam texfield
        idPelangganView.setText(id);
        namaPelangganView.setText(nama);
        nomorHpView.setText(nohp);
        if(jk.equals("Pria")){
            pria.setSelected(true);
        }
        else{
            wanita.setSelected(true);
        }
        umur.setText(umr);
        alamat.setText(almt);
        
        cP.kontrolButtonDua();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_id = new javax.swing.JLabel();
        idPelangganView = new javax.swing.JTextField();
        lb_nama = new javax.swing.JLabel();
        namaPelangganView = new javax.swing.JTextField();
        lb_noHp = new javax.swing.JLabel();
        nomorHpView = new javax.swing.JTextField();
        lb_jk = new javax.swing.JLabel();
        pria = new javax.swing.JRadioButton();
        wanita = new javax.swing.JRadioButton();
        umur = new javax.swing.JTextField();
        lb_umur = new javax.swing.JLabel();
        lb_alamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        tombolSimpan = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolBatal = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modul Pelanggan");

        lb_id.setText("ID Pelanggan");

        idPelangganView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPelangganViewActionPerformed(evt);
            }
        });

        lb_nama.setText("Nama Pelanggan");

        namaPelangganView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPelangganViewActionPerformed(evt);
            }
        });

        lb_noHp.setText("Nomor Handphone");

        nomorHpView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomorHpViewActionPerformed(evt);
            }
        });

        lb_jk.setText("Jenis Kelamin");

        pria.setText("Pria");
        pria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priaActionPerformed(evt);
            }
        });

        wanita.setText("Wanita");
        wanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wanitaActionPerformed(evt);
            }
        });

        umur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umurActionPerformed(evt);
            }
        });

        lb_umur.setText("Umur");

        lb_alamat.setText("Alamat");

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        tombolSimpan.setText("SIMPAN");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });

        tombolUbah.setText("UBAH");
        tombolUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolUbahActionPerformed(evt);
            }
        });

        tombolBatal.setText("BATAL");
        tombolBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBatalActionPerformed(evt);
            }
        });

        tombolHapus.setText("HAPUS");
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "No. HP", "Jenis Kelamin", "Umur", "Alamat"
            }
        ));
        tabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(tombolBatal)
                        .addGap(45, 45, 45)
                        .addComponent(tombolHapus)
                        .addGap(41, 41, 41)
                        .addComponent(tombolUbah)
                        .addGap(37, 37, 37)
                        .addComponent(tombolSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_noHp)
                            .addComponent(lb_jk)
                            .addComponent(lb_umur)
                            .addComponent(lb_alamat)
                            .addComponent(lb_nama)
                            .addComponent(lb_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pria)
                                .addGap(63, 63, 63)
                                .addComponent(wanita))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idPelangganView, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(namaPelangganView, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nomorHpView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_id)
                            .addComponent(idPelangganView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nama)
                            .addComponent(namaPelangganView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_noHp)
                            .addComponent(nomorHpView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pria)
                            .addComponent(wanita)
                            .addComponent(lb_jk))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_umur)
                            .addComponent(umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_alamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombolBatal)
                            .addComponent(tombolUbah)
                            .addComponent(tombolSimpan)
                            .addComponent(tombolHapus)))
                    .addComponent(jScrollPane2))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idPelangganViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPelangganViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganViewActionPerformed

    private void namaPelangganViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPelangganViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPelangganViewActionPerformed

    private void nomorHpViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorHpViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorHpViewActionPerformed

    private void priaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priaActionPerformed

    private void umurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_umurActionPerformed

    private void wanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wanitaActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        cP.simpan();
        tampilDataPelanggan();
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        // TODO add your handling code here:
        cP.delete();
        tampilDataPelanggan();
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBatalActionPerformed
        // TODO add your handling code here:
        cP.kontrolButton();
        cP.bersihkan();
    }//GEN-LAST:event_tombolBatalActionPerformed

    private void tabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPelangganMouseClicked
        // TODO add your handling code here:
        ambilDataTabel();
    }//GEN-LAST:event_tabelPelangganMouseClicked

    private void tombolUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolUbahActionPerformed
        // TODO add your handling code here:
        cP.update();
        tampilDataPelanggan();
    }//GEN-LAST:event_tombolUbahActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField idPelangganView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_alamat;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_jk;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_noHp;
    private javax.swing.JLabel lb_umur;
    private javax.swing.JTextField namaPelangganView;
    private javax.swing.JTextField nomorHpView;
    private javax.swing.JRadioButton pria;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JButton tombolBatal;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    private javax.swing.JTextField umur;
    private javax.swing.JRadioButton wanita;
    // End of variables declaration//GEN-END:variables
}
