
package ryan.ramadhan.view;

import ryan.ramadhan.controller.controllerTransaksi;
import ryan.ramadhan.db.KoneksiDatabase;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 * @author Ryan Ramadhan || 1910631170229
 */

public class viewTransaksi extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewTransaksi
     */
    
    private controllerTransaksi cT;
    private DefaultTableModel model;
    public LocalDate sekarang = LocalDate.now();
    
    public viewTransaksi() {
        initComponents();
        
        model = new DefaultTableModel();
        tabelTransaksi.setModel(model);
        
        model.addColumn("nama barang");
        model.addColumn("harga barang");
        model.addColumn("qty barang");
        model.addColumn("sub total bayar");
        totalBayar.setText("0");
        
        cT = new controllerTransaksi(this);
    }

    public JTextArea getAlamatPelanggan() {
        return alamatPelanggan;
    }

    public void setAlamatPelanggan(JTextArea alamatPelanggan) {
        this.alamatPelanggan = alamatPelanggan;
    }

    public JTextField getHargaBarang() {
        return hargaBarang;
    }

    public void setHargaBarang(JTextField hargaBarang) {
        this.hargaBarang = hargaBarang;
    }

    public JTextField getIdPelanggan() {
        return idPelanggan;
    }

    public void setIdPelanggan(JTextField idPelanggan) {
        this.idPelanggan = idPelanggan;
    }

    public JTextField getJenisKelamin() {
        return jenisKelamin;
    }

    public void setJenisKelamin(JTextField jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }

    public JTextField getNamaBarang() {
        return namaBarang;
    }

    public void setNamaBarang(JTextField namaBarang) {
        this.namaBarang = namaBarang;
    }

    public JTextField getNamaPelanggan() {
        return namaPelanggan;
    }

    public void setNamaPelanggan(JTextField namaPelanggan) {
        this.namaPelanggan = namaPelanggan;
    }

    public JTextField getNomorHp() {
        return nomorHp;
    }

    public void setNomorHp(JTextField nomorHp) {
        this.nomorHp = nomorHp;
    }

    public JTextField getQty() {
        return qty;
    }

    public void setQty(JTextField qty) {
        this.qty = qty;
    }

    public JTextField getTotalBayar() {
        return totalBayar;
    }

    public void setTotalBayar(JTextField totalBayar) {
        this.totalBayar = totalBayar;
    }

    public JTextField getUangBayar() {
        return uangBayar;
    }

    public void setUangBayar(JTextField uangBayar) {
        this.uangBayar = uangBayar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_pembelian = new javax.swing.JPanel();
        lb_id = new javax.swing.JLabel();
        idPelanggan = new javax.swing.JTextField();
        lb_nama = new javax.swing.JLabel();
        namaPelanggan = new javax.swing.JTextField();
        lb_alamat = new javax.swing.JLabel();
        lb_nohp = new javax.swing.JLabel();
        lb_jk = new javax.swing.JLabel();
        nomorHp = new javax.swing.JTextField();
        jenisKelamin = new javax.swing.JTextField();
        cariDataPelanggan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        alamatPelanggan = new javax.swing.JTextArea();
        tb_judul = new javax.swing.JLabel();
        panel_transaksi = new javax.swing.JPanel();
        lb_namabarang = new javax.swing.JLabel();
        lb_harga = new javax.swing.JLabel();
        hargaBarang = new javax.swing.JTextField();
        lb_harga1 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        tambahBarang = new javax.swing.JButton();
        namaBarang = new javax.swing.JTextField();
        CariBarang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lb_bayar = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        uangBayar = new javax.swing.JTextField();
        lb_total = new javax.swing.JLabel();
        prosesTransaksi = new javax.swing.JButton();
        batalTransaksi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panel_pembelian.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pelanggan - Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lb_id.setText("Id Pelanggan");

        lb_nama.setText("Nama Pelanggan");

        namaPelanggan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaPelangganFocusGained(evt);
            }
        });
        namaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPelangganActionPerformed(evt);
            }
        });

        lb_alamat.setText("Alamat");

        lb_nohp.setText("Nomor HP");

        lb_jk.setText("Jenis Kelamin");

        cariDataPelanggan.setText("Cari Data Pelanggan");
        cariDataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariDataPelangganActionPerformed(evt);
            }
        });

        alamatPelanggan.setColumns(20);
        alamatPelanggan.setRows(5);
        jScrollPane3.setViewportView(alamatPelanggan);

        javax.swing.GroupLayout panel_pembelianLayout = new javax.swing.GroupLayout(panel_pembelian);
        panel_pembelian.setLayout(panel_pembelianLayout);
        panel_pembelianLayout.setHorizontalGroup(
            panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nama)
                    .addComponent(lb_alamat)
                    .addComponent(lb_id))
                .addGap(52, 52, 52)
                .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namaPelanggan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addGap(104, 104, 104)
                .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nohp)
                    .addComponent(lb_jk))
                .addGap(49, 49, 49)
                .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nomorHp, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(jenisKelamin))
                    .addComponent(cariDataPelanggan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_pembelianLayout.setVerticalGroup(
            panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pembelianLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_pembelianLayout.createSequentialGroup()
                        .addComponent(lb_id)
                        .addGap(26, 26, 26)
                        .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nama)
                            .addComponent(namaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_pembelianLayout.createSequentialGroup()
                        .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nohp)
                            .addComponent(nomorHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_jk)
                            .addComponent(jenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(panel_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_alamat)
                    .addComponent(cariDataPelanggan)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tb_judul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tb_judul.setText("FORM TRANSAKSI BARANG");

        panel_transaksi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Barang - Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        lb_namabarang.setText("Nama Barang");

        lb_harga.setText("Harga Barang");

        lb_harga1.setText("Qty Beli");

        tambahBarang.setText("Tambah Barang");
        tambahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangActionPerformed(evt);
            }
        });

        namaBarang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namaBarangFocusGained(evt);
            }
        });

        CariBarang.setText("Cari Barang");
        CariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_transaksiLayout = new javax.swing.GroupLayout(panel_transaksi);
        panel_transaksi.setLayout(panel_transaksiLayout);
        panel_transaksiLayout.setHorizontalGroup(
            panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_transaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_harga)
                    .addComponent(lb_namabarang))
                .addGap(69, 69, 69)
                .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hargaBarang)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(lb_harga1)
                .addGap(73, 73, 73)
                .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_transaksiLayout.createSequentialGroup()
                        .addComponent(CariBarang)
                        .addGap(18, 18, 18)
                        .addComponent(tambahBarang)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panel_transaksiLayout.setVerticalGroup(
            panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_transaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_transaksiLayout.createSequentialGroup()
                        .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_harga1))
                            .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_namabarang)
                                .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_transaksiLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lb_harga))
                            .addGroup(panel_transaksiLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel_transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CariBarang)
                                    .addComponent(tambahBarang))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        lb_bayar.setText("Uang Bayar");

        lb_total.setText("Total Bayar");

        prosesTransaksi.setText("Proses Transaksi");
        prosesTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesTransaksiActionPerformed(evt);
            }
        });

        batalTransaksi.setText("Batal Transaksi");
        batalTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalTransaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_bayar)
                    .addComponent(lb_total))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(batalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(prosesTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(batalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prosesTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_total))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uangBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_bayar))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "title 1", "title 2", "title 3", "title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tb_judul)
                .addGap(326, 326, 326))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(panel_pembelian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_transaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tb_judul)
                .addGap(18, 18, 18)
                .addComponent(panel_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariDataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariDataPelangganActionPerformed
        //Ryan Ramadhan || 1910631170229
        viewListDataPelanggan vldp = new viewListDataPelanggan(this);
        vldp.setVisible(true);
    }//GEN-LAST:event_cariDataPelangganActionPerformed

    private void tambahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangActionPerformed
        //Ryan Ramadhan || 1910631170229
        Object[] hasil;
        hasil = new Object[4];
        hasil[0] = namaBarang.getText();
        hasil[1] = hargaBarang.getText();
        hasil[2] = qty.getText();
        hasil[3] = Integer.parseInt(qty.getText()) * Integer.parseInt(hargaBarang.getText());
        
        model.addRow(hasil);
        
        //Menghitung total nominal belanja
        //inisialisasi variabel
        Integer total = 0;
        
        //Cek apakah tabel transaksi sudah ada atau belum datanya
        if(Integer.parseInt(totalBayar.getText()) == 0){
            int subtotal = Integer.parseInt(tabelTransaksi.getValueAt(0, 3).toString());
            total = subtotal;
            totalBayar.setText(String.valueOf(total));
        }
        else{   //jika tabel transaksi ada datanya
            for(int index = 0; index<model.getRowCount(); index++){
                //looping dilakukan untuk menjumlahkan subtotal sesuai dengan banyaknya barang
                int subtotal = Integer.parseInt(tabelTransaksi.getValueAt(index, 3).toString());
                total = total + subtotal;
            }
            //setText untuk hasil penjumlahan barang dengan subtotal
            totalBayar.setText(String.valueOf(total));
        } 
    }//GEN-LAST:event_tambahBarangActionPerformed

    private void prosesTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesTransaksiActionPerformed
        //Ryan Ramadhan || 1910631170229
        int jumlahRow = tabelTransaksi.getRowCount();
        Object[][] hasil;
        hasil = new Object[4][4];
        
        //Lakukan ;ooping untuk mengambil data barang pada tabelTransaksi
        for(int x = 0; x < jumlahRow; x++){
            //ambil value kolom pertama [x] => adalah row ke-x, sesuai value variabel
            hasil[x][0] = tabelTransaksi.getValueAt(x, 0).toString();
            hasil[x][1] = tabelTransaksi.getValueAt(x, 1).toString();
            hasil[x][2] = tabelTransaksi.getValueAt(x, 2).toString();
            hasil[x][3] = tabelTransaksi.getValueAt(x, 3).toString();
            
            String sql = "INSERT INTO transaksiDetail (namaBarang"
                    +", qty, subTotal, tanggal) VALUES ('"+hasil[x][0]+"','"+hasil[x][2]+"','"+hasil[x][3]+"'"
                    +", '"+sekarang+"')";
            
            try{
                PreparedStatement eksekusi = KoneksiDatabase.getKoneksi().prepareStatement(sql);
                eksekusi.execute();
            
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan\n"+ ex);
            }
        }
        cT.simpanTransaksi();
    }//GEN-LAST:event_prosesTransaksiActionPerformed

    private void batalTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalTransaksiActionPerformed
        // TODO add your handling code here:
        cT.bersihkan();
        model.setRowCount(0);
    }//GEN-LAST:event_batalTransaksiActionPerformed

    private void namaPelangganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaPelangganFocusGained
        //Ryan Ramadhan || 1910631170229
        //viewListDataPelanggan vldp = new viewListDataPelanggan(this);
        //vldp.setVisible(true);
    }//GEN-LAST:event_namaPelangganFocusGained

    private void namaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPelangganActionPerformed

    }//GEN-LAST:event_namaPelangganActionPerformed

    private void namaBarangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namaBarangFocusGained
        // TODO add your handling code here:
        viewListDataBarang vld = new viewListDataBarang(this);
        vld.setVisible(true);
    }//GEN-LAST:event_namaBarangFocusGained

    private void CariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariBarangActionPerformed
        // TODO add your handling code here:
        viewListDataBarang vld = new viewListDataBarang(this);
        vld.setVisible(true);
    }//GEN-LAST:event_CariBarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CariBarang;
    private javax.swing.JTextArea alamatPelanggan;
    private javax.swing.JButton batalTransaksi;
    private javax.swing.JButton cariDataPelanggan;
    private javax.swing.JTextField hargaBarang;
    private javax.swing.JTextField idPelanggan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jenisKelamin;
    private javax.swing.JLabel lb_alamat;
    private javax.swing.JLabel lb_bayar;
    private javax.swing.JLabel lb_harga;
    private javax.swing.JLabel lb_harga1;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_jk;
    private javax.swing.JLabel lb_nama;
    private javax.swing.JLabel lb_namabarang;
    private javax.swing.JLabel lb_nohp;
    private javax.swing.JLabel lb_total;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTextField namaPelanggan;
    private javax.swing.JTextField nomorHp;
    private javax.swing.JPanel panel_pembelian;
    private javax.swing.JPanel panel_transaksi;
    private javax.swing.JButton prosesTransaksi;
    private javax.swing.JTextField qty;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tambahBarang;
    private javax.swing.JLabel tb_judul;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JTextField uangBayar;
    // End of variables declaration//GEN-END:variables
}
